/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const TrackId = IDL.Nat;
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const TrackInput = IDL.Record({
  'title' : IDL.Text,
  'album' : IDL.Text,
  'audioFile' : ExternalBlob,
  'coverImage' : ExternalBlob,
  'sellerName' : IDL.Text,
  'artist' : IDL.Text,
  'priceUSD' : IDL.Float64,
});
export const LyricId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const LyricEntry = IDL.Record({
  'id' : LyricId,
  'contributorName' : IDL.Text,
  'yearReleased' : IDL.Nat,
  'title' : IDL.Text,
  'album' : IDL.Text,
  'lyrics' : IDL.Text,
  'contributorId' : UserId,
  'submittedAt' : Timestamp,
  'viewCount' : IDL.Nat,
  'notes' : IDL.Text,
  'artist' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TrackView = IDL.Record({
  'id' : TrackId,
  'title' : IDL.Text,
  'album' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : Timestamp,
  'audioFile' : ExternalBlob,
  'coverImage' : ExternalBlob,
  'sellerName' : IDL.Text,
  'viewCount' : IDL.Nat,
  'artist' : IDL.Text,
  'sellerId' : UserId,
  'priceUSD' : IDL.Float64,
});
export const PurchaseRecord = IDL.Record({
  'trackId' : TrackId,
  'buyerId' : UserId,
  'sessionId' : IDL.Text,
  'paidAt' : Timestamp,
});
export const SortOrder = IDL.Variant({
  'titleDesc' : IDL.Null,
  'newest' : IDL.Null,
  'priceDesc' : IDL.Null,
  'priceAsc' : IDL.Null,
  'titleAsc' : IDL.Null,
  'oldest' : IDL.Null,
});
export const MusicSearchParams = IDL.Record({
  'sortOrder' : IDL.Opt(SortOrder),
  'searchText' : IDL.Opt(IDL.Text),
  'artist' : IDL.Opt(IDL.Text),
});
export const SortOrder__1 = IDL.Variant({
  'mostRecent' : IDL.Null,
  'alphabetical' : IDL.Null,
  'mostViewed' : IDL.Null,
});
export const SearchParams = IDL.Record({
  'yearFilter' : IDL.Opt(IDL.Nat),
  'artistFilter' : IDL.Opt(IDL.Text),
  'sortOrder' : SortOrder__1,
  'searchText' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const LyricInput = IDL.Record({
  'yearReleased' : IDL.Nat,
  'title' : IDL.Text,
  'album' : IDL.Text,
  'lyrics' : IDL.Text,
  'notes' : IDL.Text,
  'artist' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'buildTrackShoppingItem' : IDL.Func([TrackId], [ShoppingItem], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'editTrack' : IDL.Func([TrackId, TrackInput], [], []),
  'getLyric' : IDL.Func([LyricId], [IDL.Opt(LyricEntry)], []),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTrack' : IDL.Func([TrackId], [IDL.Opt(TrackView)], []),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listArtists' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listLyrics' : IDL.Func([], [IDL.Vec(LyricEntry)], ['query']),
  'listPurchases' : IDL.Func([UserId], [IDL.Vec(PurchaseRecord)], ['query']),
  'listSellerTracks' : IDL.Func([UserId], [IDL.Vec(TrackView)], ['query']),
  'listTracks' : IDL.Func(
      [IDL.Opt(MusicSearchParams)],
      [IDL.Vec(TrackView)],
      ['query'],
    ),
  'publishTrack' : IDL.Func([TrackInput], [TrackId], []),
  'recordTrackPurchase' : IDL.Func([IDL.Text, TrackId], [], []),
  'republishTrack' : IDL.Func([TrackId], [], []),
  'searchLyrics' : IDL.Func([SearchParams], [IDL.Vec(LyricEntry)], ['query']),
  'searchTracks' : IDL.Func(
      [MusicSearchParams],
      [IDL.Vec(TrackView)],
      ['query'],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitLyric' : IDL.Func([LyricInput], [LyricId], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unpublishTrack' : IDL.Func([TrackId], [], []),
  'updateLyric' : IDL.Func([LyricId, LyricInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const TrackId = IDL.Nat;
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const TrackInput = IDL.Record({
    'title' : IDL.Text,
    'album' : IDL.Text,
    'audioFile' : ExternalBlob,
    'coverImage' : ExternalBlob,
    'sellerName' : IDL.Text,
    'artist' : IDL.Text,
    'priceUSD' : IDL.Float64,
  });
  const LyricId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const LyricEntry = IDL.Record({
    'id' : LyricId,
    'contributorName' : IDL.Text,
    'yearReleased' : IDL.Nat,
    'title' : IDL.Text,
    'album' : IDL.Text,
    'lyrics' : IDL.Text,
    'contributorId' : UserId,
    'submittedAt' : Timestamp,
    'viewCount' : IDL.Nat,
    'notes' : IDL.Text,
    'artist' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TrackView = IDL.Record({
    'id' : TrackId,
    'title' : IDL.Text,
    'album' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : Timestamp,
    'audioFile' : ExternalBlob,
    'coverImage' : ExternalBlob,
    'sellerName' : IDL.Text,
    'viewCount' : IDL.Nat,
    'artist' : IDL.Text,
    'sellerId' : UserId,
    'priceUSD' : IDL.Float64,
  });
  const PurchaseRecord = IDL.Record({
    'trackId' : TrackId,
    'buyerId' : UserId,
    'sessionId' : IDL.Text,
    'paidAt' : Timestamp,
  });
  const SortOrder = IDL.Variant({
    'titleDesc' : IDL.Null,
    'newest' : IDL.Null,
    'priceDesc' : IDL.Null,
    'priceAsc' : IDL.Null,
    'titleAsc' : IDL.Null,
    'oldest' : IDL.Null,
  });
  const MusicSearchParams = IDL.Record({
    'sortOrder' : IDL.Opt(SortOrder),
    'searchText' : IDL.Opt(IDL.Text),
    'artist' : IDL.Opt(IDL.Text),
  });
  const SortOrder__1 = IDL.Variant({
    'mostRecent' : IDL.Null,
    'alphabetical' : IDL.Null,
    'mostViewed' : IDL.Null,
  });
  const SearchParams = IDL.Record({
    'yearFilter' : IDL.Opt(IDL.Nat),
    'artistFilter' : IDL.Opt(IDL.Text),
    'sortOrder' : SortOrder__1,
    'searchText' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const LyricInput = IDL.Record({
    'yearReleased' : IDL.Nat,
    'title' : IDL.Text,
    'album' : IDL.Text,
    'lyrics' : IDL.Text,
    'notes' : IDL.Text,
    'artist' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'buildTrackShoppingItem' : IDL.Func([TrackId], [ShoppingItem], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'editTrack' : IDL.Func([TrackId, TrackInput], [], []),
    'getLyric' : IDL.Func([LyricId], [IDL.Opt(LyricEntry)], []),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTrack' : IDL.Func([TrackId], [IDL.Opt(TrackView)], []),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listArtists' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listLyrics' : IDL.Func([], [IDL.Vec(LyricEntry)], ['query']),
    'listPurchases' : IDL.Func([UserId], [IDL.Vec(PurchaseRecord)], ['query']),
    'listSellerTracks' : IDL.Func([UserId], [IDL.Vec(TrackView)], ['query']),
    'listTracks' : IDL.Func(
        [IDL.Opt(MusicSearchParams)],
        [IDL.Vec(TrackView)],
        ['query'],
      ),
    'publishTrack' : IDL.Func([TrackInput], [TrackId], []),
    'recordTrackPurchase' : IDL.Func([IDL.Text, TrackId], [], []),
    'republishTrack' : IDL.Func([TrackId], [], []),
    'searchLyrics' : IDL.Func([SearchParams], [IDL.Vec(LyricEntry)], ['query']),
    'searchTracks' : IDL.Func(
        [MusicSearchParams],
        [IDL.Vec(TrackView)],
        ['query'],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitLyric' : IDL.Func([LyricInput], [LyricId], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unpublishTrack' : IDL.Func([TrackId], [], []),
    'updateLyric' : IDL.Func([LyricId, LyricInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };