/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface LyricEntry {
  'id' : LyricId,
  'contributorName' : string,
  'yearReleased' : bigint,
  'title' : string,
  'album' : string,
  'lyrics' : string,
  'contributorId' : UserId,
  'submittedAt' : Timestamp,
  'viewCount' : bigint,
  'notes' : string,
  'artist' : string,
}
export type LyricId = bigint;
export interface LyricInput {
  'yearReleased' : bigint,
  'title' : string,
  'album' : string,
  'lyrics' : string,
  'notes' : string,
  'artist' : string,
}
export interface MusicSearchParams {
  'sortOrder' : [] | [SortOrder],
  'searchText' : [] | [string],
  'artist' : [] | [string],
}
export interface PurchaseRecord {
  'trackId' : TrackId,
  'buyerId' : UserId,
  'sessionId' : string,
  'paidAt' : Timestamp,
}
export interface SearchParams {
  'yearFilter' : [] | [bigint],
  'artistFilter' : [] | [string],
  'sortOrder' : SortOrder__1,
  'searchText' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type SortOrder = { 'titleDesc' : null } |
  { 'newest' : null } |
  { 'priceDesc' : null } |
  { 'priceAsc' : null } |
  { 'titleAsc' : null } |
  { 'oldest' : null };
export type SortOrder__1 = { 'mostRecent' : null } |
  { 'alphabetical' : null } |
  { 'mostViewed' : null };
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export type TrackId = bigint;
export interface TrackInput {
  'title' : string,
  'album' : string,
  'audioFile' : ExternalBlob,
  'coverImage' : ExternalBlob,
  'sellerName' : string,
  'artist' : string,
  'priceUSD' : number,
}
export interface TrackView {
  'id' : TrackId,
  'title' : string,
  'album' : string,
  'published' : boolean,
  'createdAt' : Timestamp,
  'audioFile' : ExternalBlob,
  'coverImage' : ExternalBlob,
  'sellerName' : string,
  'viewCount' : bigint,
  'artist' : string,
  'sellerId' : UserId,
  'priceUSD' : number,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'buildTrackShoppingItem' : ActorMethod<[TrackId], ShoppingItem>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'editTrack' : ActorMethod<[TrackId, TrackInput], undefined>,
  'getLyric' : ActorMethod<[LyricId], [] | [LyricEntry]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTrack' : ActorMethod<[TrackId], [] | [TrackView]>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listArtists' : ActorMethod<[], Array<string>>,
  'listLyrics' : ActorMethod<[], Array<LyricEntry>>,
  'listPurchases' : ActorMethod<[UserId], Array<PurchaseRecord>>,
  'listSellerTracks' : ActorMethod<[UserId], Array<TrackView>>,
  'listTracks' : ActorMethod<[[] | [MusicSearchParams]], Array<TrackView>>,
  'publishTrack' : ActorMethod<[TrackInput], TrackId>,
  'recordTrackPurchase' : ActorMethod<[string, TrackId], undefined>,
  'republishTrack' : ActorMethod<[TrackId], undefined>,
  'searchLyrics' : ActorMethod<[SearchParams], Array<LyricEntry>>,
  'searchTracks' : ActorMethod<[MusicSearchParams], Array<TrackView>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitLyric' : ActorMethod<[LyricInput], LyricId>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unpublishTrack' : ActorMethod<[TrackId], undefined>,
  'updateLyric' : ActorMethod<[LyricId, LyricInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];