/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface LyricEntry {
    id: LyricId;
    contributorName: string;
    yearReleased: bigint;
    title: string;
    album: string;
    lyrics: string;
    contributorId: UserId;
    submittedAt: Timestamp;
    viewCount: bigint;
    notes: string;
    artist: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SearchParams {
    yearFilter?: bigint;
    artistFilter?: string;
    sortOrder: SortOrder__1;
    searchText: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface TrackView {
    id: TrackId;
    title: string;
    album: string;
    published: boolean;
    createdAt: Timestamp;
    audioFile: ExternalBlob;
    coverImage: ExternalBlob;
    sellerName: string;
    viewCount: bigint;
    artist: string;
    sellerId: UserId;
    priceUSD: number;
}
export type UserId = Principal;
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface MusicSearchParams {
    sortOrder?: SortOrder;
    searchText?: string;
    artist?: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface TrackInput {
    title: string;
    album: string;
    audioFile: ExternalBlob;
    coverImage: ExternalBlob;
    sellerName: string;
    artist: string;
    priceUSD: number;
}
export type TrackId = bigint;
export interface PurchaseRecord {
    trackId: TrackId;
    buyerId: UserId;
    sessionId: string;
    paidAt: Timestamp;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface LyricInput {
    yearReleased: bigint;
    title: string;
    album: string;
    lyrics: string;
    notes: string;
    artist: string;
}
export type LyricId = bigint;
export enum SortOrder {
    titleDesc = "titleDesc",
    newest = "newest",
    priceDesc = "priceDesc",
    priceAsc = "priceAsc",
    titleAsc = "titleAsc",
    oldest = "oldest"
}
export enum SortOrder__1 {
    mostRecent = "mostRecent",
    alphabetical = "alphabetical",
    mostViewed = "mostViewed"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    buildTrackShoppingItem(trackId: TrackId): Promise<ShoppingItem>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    editTrack(id: TrackId, input: TrackInput): Promise<void>;
    getLyric(id: LyricId): Promise<LyricEntry | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTrack(id: TrackId): Promise<TrackView | null>;
    isStripeConfigured(): Promise<boolean>;
    listArtists(): Promise<Array<string>>;
    listLyrics(): Promise<Array<LyricEntry>>;
    listPurchases(buyerId: UserId): Promise<Array<PurchaseRecord>>;
    listSellerTracks(sellerId: UserId): Promise<Array<TrackView>>;
    listTracks(params: MusicSearchParams | null): Promise<Array<TrackView>>;
    publishTrack(input: TrackInput): Promise<TrackId>;
    recordTrackPurchase(sessionId: string, trackId: TrackId): Promise<void>;
    republishTrack(id: TrackId): Promise<void>;
    searchLyrics(params: SearchParams): Promise<Array<LyricEntry>>;
    searchTracks(params: MusicSearchParams): Promise<Array<TrackView>>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitLyric(input: LyricInput): Promise<LyricId>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unpublishTrack(id: TrackId): Promise<void>;
    updateLyric(id: LyricId, input: LyricInput): Promise<boolean>;
}
import type { ExternalBlob as _ExternalBlob, LyricEntry as _LyricEntry, MusicSearchParams as _MusicSearchParams, SearchParams as _SearchParams, SortOrder as _SortOrder, SortOrder__1 as _SortOrder__1, StripeSessionStatus as _StripeSessionStatus, Timestamp as _Timestamp, TrackId as _TrackId, TrackInput as _TrackInput, TrackView as _TrackView, UserId as _UserId, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async buildTrackShoppingItem(arg0: TrackId): Promise<ShoppingItem> {
        if (this.processError) {
            try {
                const result = await this.actor.buildTrackShoppingItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buildTrackShoppingItem(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async editTrack(arg0: TrackId, arg1: TrackInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editTrack(arg0, await to_candid_TrackInput_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editTrack(arg0, await to_candid_TrackInput_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getLyric(arg0: LyricId): Promise<LyricEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLyric(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLyric(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrack(arg0: TrackId): Promise<TrackView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrack(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrack(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listArtists(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.listArtists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listArtists();
            return result;
        }
    }
    async listLyrics(): Promise<Array<LyricEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLyrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLyrics();
            return result;
        }
    }
    async listPurchases(arg0: UserId): Promise<Array<PurchaseRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPurchases(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPurchases(arg0);
            return result;
        }
    }
    async listSellerTracks(arg0: UserId): Promise<Array<TrackView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSellerTracks(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSellerTracks(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTracks(arg0: MusicSearchParams | null): Promise<Array<TrackView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTracks(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTracks(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async publishTrack(arg0: TrackInput): Promise<TrackId> {
        if (this.processError) {
            try {
                const result = await this.actor.publishTrack(await to_candid_TrackInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishTrack(await to_candid_TrackInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async recordTrackPurchase(arg0: string, arg1: TrackId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordTrackPurchase(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordTrackPurchase(arg0, arg1);
            return result;
        }
    }
    async republishTrack(arg0: TrackId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.republishTrack(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.republishTrack(arg0);
            return result;
        }
    }
    async searchLyrics(arg0: SearchParams): Promise<Array<LyricEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchLyrics(to_candid_SearchParams_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchLyrics(to_candid_SearchParams_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchTracks(arg0: MusicSearchParams): Promise<Array<TrackView>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTracks(to_candid_MusicSearchParams_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTracks(to_candid_MusicSearchParams_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitLyric(arg0: LyricInput): Promise<LyricId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLyric(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLyric(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unpublishTrack(arg0: TrackId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unpublishTrack(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpublishTrack(arg0);
            return result;
        }
    }
    async updateLyric(arg0: LyricId, arg1: LyricInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLyric(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLyric(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_StripeSessionStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function from_candid_TrackView_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrackView): Promise<TrackView> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LyricEntry]): LyricEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TrackView]): Promise<TrackView | null> {
    return value.length === 0 ? null : await from_candid_TrackView_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TrackId;
    title: string;
    album: string;
    published: boolean;
    createdAt: _Timestamp;
    audioFile: _ExternalBlob;
    coverImage: _ExternalBlob;
    sellerName: string;
    viewCount: bigint;
    artist: string;
    sellerId: _UserId;
    priceUSD: number;
}): Promise<{
    id: TrackId;
    title: string;
    album: string;
    published: boolean;
    createdAt: Timestamp;
    audioFile: ExternalBlob;
    coverImage: ExternalBlob;
    sellerName: string;
    viewCount: bigint;
    artist: string;
    sellerId: UserId;
    priceUSD: number;
}> {
    return {
        id: value.id,
        title: value.title,
        album: value.album,
        published: value.published,
        createdAt: value.createdAt,
        audioFile: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.audioFile),
        coverImage: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.coverImage),
        sellerName: value.sellerName,
        viewCount: value.viewCount,
        artist: value.artist,
        sellerId: value.sellerId,
        priceUSD: value.priceUSD
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n14(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrackView>): Promise<Array<TrackView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TrackView_n17(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MusicSearchParams_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MusicSearchParams): _MusicSearchParams {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_SearchParams_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchParams): _SearchParams {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_SortOrder__1_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder__1): _SortOrder__1 {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_SortOrder_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): _SortOrder {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
async function to_candid_TrackInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrackInput): Promise<_TrackInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MusicSearchParams | null): [] | [_MusicSearchParams] {
    return value === null ? candid_none() : candid_some(to_candid_MusicSearchParams_n22(_uploadFile, _downloadFile, value));
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sortOrder?: SortOrder;
    searchText?: string;
    artist?: string;
}): {
    sortOrder: [] | [_SortOrder];
    searchText: [] | [string];
    artist: [] | [string];
} {
    return {
        sortOrder: value.sortOrder ? candid_some(to_candid_SortOrder_n24(_uploadFile, _downloadFile, value.sortOrder)) : candid_none(),
        searchText: value.searchText ? candid_some(value.searchText) : candid_none(),
        artist: value.artist ? candid_some(value.artist) : candid_none()
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    yearFilter?: bigint;
    artistFilter?: string;
    sortOrder: SortOrder__1;
    searchText: string;
}): {
    yearFilter: [] | [bigint];
    artistFilter: [] | [string];
    sortOrder: _SortOrder__1;
    searchText: string;
} {
    return {
        yearFilter: value.yearFilter ? candid_some(value.yearFilter) : candid_none(),
        artistFilter: value.artistFilter ? candid_some(value.artistFilter) : candid_none(),
        sortOrder: to_candid_SortOrder__1_n28(_uploadFile, _downloadFile, value.sortOrder),
        searchText: value.searchText
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    album: string;
    audioFile: ExternalBlob;
    coverImage: ExternalBlob;
    sellerName: string;
    artist: string;
    priceUSD: number;
}): Promise<{
    title: string;
    album: string;
    audioFile: _ExternalBlob;
    coverImage: _ExternalBlob;
    sellerName: string;
    artist: string;
    priceUSD: number;
}> {
    return {
        title: value.title,
        album: value.album,
        audioFile: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.audioFile),
        coverImage: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.coverImage),
        sellerName: value.sellerName,
        artist: value.artist,
        priceUSD: value.priceUSD
    };
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): {
    titleDesc: null;
} | {
    newest: null;
} | {
    priceDesc: null;
} | {
    priceAsc: null;
} | {
    titleAsc: null;
} | {
    oldest: null;
} {
    return value == SortOrder.titleDesc ? {
        titleDesc: null
    } : value == SortOrder.newest ? {
        newest: null
    } : value == SortOrder.priceDesc ? {
        priceDesc: null
    } : value == SortOrder.priceAsc ? {
        priceAsc: null
    } : value == SortOrder.titleAsc ? {
        titleAsc: null
    } : value == SortOrder.oldest ? {
        oldest: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder__1): {
    mostRecent: null;
} | {
    alphabetical: null;
} | {
    mostViewed: null;
} {
    return value == SortOrder__1.mostRecent ? {
        mostRecent: null
    } : value == SortOrder__1.alphabetical ? {
        alphabetical: null
    } : value == SortOrder__1.mostViewed ? {
        mostViewed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
